# oama authorize microsoft your.address@cern.ch --device
encryption:
    tag: KEYRING

services:
    microsoft:
        client_id: 9e5f94bc-e8a4-4e73-b8be-63364c29d753
        tenant: common
        auth_scope: https://outlook.office.com/IMAP.AccessAsUser.All
          https://outlook.office.com/SMTP.Send
          offline_access
        tenant: c80d3499-4a40-4a8c-986e-abce017d6b19
